language: php

services:
  # - docker we should use our own docker image
  # same using waiting for the database to start
  - mysql

branches:
  except:
    - build

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

sudo: false

env:
  global:
    - DIRECTUS_DB_NAME=directus
    - DIRECTUS_DB_PASSWORD=
    - DIRECTUS_DB_USER=root
    - DIRECTUS_PATH=/
    - DIRECTUS_ADMIN_EMAIL=admin@getdirectus.com
    - DIRECTUS_ADMIN_TOKEN=token
    - DIRECTUS_ADMIN_PASSWORD=password
    - DIRECTUS_SITE_NAME=Directus
  matrix:
    - MYSQL_VERSION=5.5 DIRECTUS_TEST_MODE=IO

before_install:
  - mysql -V
  - mysql -uroot -e "DROP DATABASE IF EXISTS $DIRECTUS_DB_NAME;"
  - mysql -uroot -e "CREATE DATABASE $DIRECTUS_DB_NAME;"
  - mysql -uroot -e 'SHOW DATABASES;'
  # - sh tests/bin/install_apache.sh
  - sudo apt-get update
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - # enable php-fpm
  - ls      ~/.phpenv/versions/$(phpenv version-name)/etc
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ls      ~/.phpenv/versions/$(phpenv version-name)/etc
  - # sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/www.conf
  - ls ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - # configure apache virtual hosts
  - sudo cp -f tests/assets/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

before_script:
  - sh tests/bin/install_directus.sh

script:
  - # npm test
  - if [ $DIRECTUS_TEST_MODE = 'IO' ]; then vendor/bin/phpunit tests/io --coverage-text --coverage-clover=coverage.clover; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
