language: php

services:
  - docker

branches:
  except:
    - build

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

sudo: false

env:
  - DIRECTUS_DB_NAME=directus
  - DIRECTUS_DB_PASSWORD=directus
  - DIRECTUS_DB_USER=directus
  - DIRECTUS_PATH=/
  - DIRECTUS_ADMIN_EMAIL=admin@getdirectus.com
  - DIRECTUS_ADMIN_PASSWORD=password
  - DIRECTUS_SITE_NAME=Directus

before_script:
  - sh tests/bin/install_directus.sh
  - sh tests/bin/install_apache.sh

script:
  - npm test
  - vendor/bin/phpunit tests/ExampleTest.php --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
